//
//  PPReports.h
//  Peoplepower
//
//  Created by Destry Teeter on 3/13/18.
//  Copyright © 2023 People Power Company. All rights reserved.
//
// The IoT Software Suite provides public online reports for different purposes.
//

#import "PPBaseModel.h"
#import "PPDeviceAlert.h"

@interface PPReports : PPBaseModel

#pragma mark - Device Alerts

/**
 * Get total device alerts
 * This reports returns total numbers of alerts generated by devices by alert types. User authentication is not required.
 *
 * @param alertType NSString Return only number of this alertType
 * @param callback PPReportAlertTypesBlock Alert Types callback block
 **/
+ (void)getTotalDeviceAlerts:(NSString * _Nullable )alertType callback:(PPReportAlertTypesBlock _Nonnull )callback;

@end
