//
//  PPTCReports.m
//  iOS_Core_Tests
//
//  Created by Destry Teeter on 3/22/18.
//  Copyright © 2023 People Power Company. All rights reserved.
//

#import "PPBaseTestCase.h"
#import <Peoplepower/PPReports.h>

static NSString *moduleName = @"Reports";

@interface PPTCReports : PPBaseTestCase

@end

@implementation PPTCReports

- (void)setUp {
    [super setUp];
}

- (void)tearDown {
    // Put teardown code here. This method is called after the invocation of each test method in the class.
    [super tearDown];
}


#pragma mark - Device Alerts

/**
 * Get total device alerts
 * This reports returns total numbers of alerts generated by devices by alert types. User authentication is not required.
 *
 * @ param alertType NSString Return only number of this alertType
 * @ param callback PPReportAlertTypesBlock Alert Types callback block
 **/
// + (void)getTotalDeviceAlerts:(NSString *)alertType callback:(PPReportAlertTypesBlock)callback;
- (void)testGetTotalDeviceAlerts {
    NSString *methodName = @"GetTotalDeviceAlerts";
    XCTestExpectation *expectation = [[XCTestExpectation alloc] initWithDescription:methodName];
    
    [self stubRequestForModule:moduleName methodName:methodName ofType:@"json" path:@"/espapi/reports/json/totalDeviceAlerts" statusCode:200 headers:nil];
    
    [PPReports getTotalDeviceAlerts:nil callback:^(NSArray *alerts, NSError *error) {

        XCTAssertNil(error);
        [expectation fulfill];
        
    }];
    
    [self waitForExpectations:@[expectation] timeout:10.0];
}

@end
