//
//  PPCircles.h
//  Peoplepower
//
//  Created by Destry Teeter on 3/13/18.
//  Copyright © 2023 People Power Company. All rights reserved.
//

#import "PPBaseModel.h"
#import "PPCircle.h"
#import "PPCirclePost.h"
#import "PPCircleFile.h"
#import "PPCircleReaction.h"
#import "PPCircleDevice.h"
#import "PPCircleDeviceCamera.h"
#import "PPCircleDevicePictureFrame.h"

@interface PPCircles : PPBaseModel

#pragma mark - Session Management

#pragma mark Circles

/**
 * Shared circles across the entire application
 */
+ (NSArray *)sharedCircles;

/**
 * Add circles.
 * Add circles to local reference.
 *
 * @param circles NSArray Array of circles to add.
 **/
+ (void)addCircles:(NSArray *)circles;

/**
 * Remove circles.
 * Remove circles from local reference.
 *
 * @param circles NSArray Array of circles to remove.
 **/
+ (void)removeCircles:(NSArray *)circles;

#pragma mark Circle Files

/**
 * Shared files across the entire application
 */
+ (NSArray *)sharedFiles;

/**
 * Add files.
 * Add files to local reference.
 *
 * @param files NSArray Array of files to add.
 **/
+ (void)addFiles:(NSArray *)files;

/**
 * Remove files.
 * Remove files from local reference.
 *
 * @param files NSArray Array of files to remove.
 **/
+ (void)removeFiles:(NSArray *)files;

#pragma mark Posts

/**
 * Shared posts across the entire application
 */
+ (NSArray *)sharedPosts;

/**
 * Add posts.
 * Add posts to local reference.
 *
 * @param posts NSArray Array of posts to add.
 **/
+ (void)addPosts:(NSArray *)posts;

/**
 * Remove posts.
 * Remove posts from local reference.
 *
 * @param posts NSArray Array of posts to remove.
 **/
+ (void)removePosts:(NSArray *)posts;

#pragma mark Devices

/**
 * Shared devices across the entire application
 */
+ (NSArray *)sharedDevices;

/**
 * Add devices.
 * Add devices to local reference.
 *
 * @param devices NSArray Array of devices to add.
 **/
+ (void)addDevices:(NSArray *)devices;

/**
 * Remove devices.
 * Remove devices from local reference.
 *
 * @param devices NSArray Array of devices to remove.
 **/
+ (void)removeDevices:(NSArray *)devices;

#pragma mark - Circles

/**
 * Create a Circle.
 * The person who creates a Circle is the Administrator, until someone upgrades the Circle into a Premium Circle (or higher). The people who pay for Premium services take over as the Administrator.
 * You are always an implied member of the Circle you create.
 * The request returns the ID of the Circle that was created, for future reference.
 * Remember that we can add email addresses without having a user account created on our system. Every user will get an email + push notification that they're part of the Circle.
 * Any accounts that are email address only will receive a daily update with the top 3 items from the conversation on what they missed out on, with an opportunity to sign up.
 *
 * @param name NSString Name of the circle
 * @param callback PPCircleCreationBlock Circle creation callback block
 **/
+ (void)createCircle:(NSString * _Nullable )name callback:(PPCircleCreationBlock _Nonnull )callback;

/**
 * Get Circles.
 * TODO: Each member must have an Avatar image associated with their user account. If that avatar image changes, then we need to know it at the app so we can update your picture - perhaps a hidden item in the feed? An Avatar image may be a picture, or it could be auto-generated by the app like a circle with your initials in it. If an image doesn't exist, we'll just assume we should auto-generate an avatar for the user.
 *
 * @param circleIds NSArray Array of Circle IDs as NSNumbers
 * @param callback PPCirclesBlock Circles callback block
 **/
+ (void)getCirclesWithCircleIds:(NSArray * _Nullable )circleIds callback:(PPCirclesBlock _Nonnull )callback;
+ (void)getCircles:(PPCircleId)circleId callback:(PPCirclesBlock _Nonnull )callback __attribute__((deprecated));

/**
 * Modify a Circle.
 * Only a Circle Administrator may modify a Circle.
 *
 * @param circleId Required PPCircleId Circle ID
 * @param name Required NSString Circle Name
 * @param callback PPErrorBlock Error callback block
 **/
+ (void)modifyCircle:(PPCircleId)circleId name:(NSString * _Nonnull )name callback:(PPErrorBlock _Nonnull )callback;

/**
 * Delete a Circle.
 * Only a Circle Administrator may delete a Circle.
 *
 * @param circleId Required PPCircleId Circle ID
 * @param callback PPErrorBlock Error callback block
 **/
+ (void)deleteCircle:(PPCircleId)circleId callback:(PPErrorBlock _Nonnull )callback;

#pragma mark - Manage Circle Members

/**
 * Add Members.
 * Any member of a circle may add more members to a circle, not just the administrator. We want to help its utility grow organically.
 * Remember that we can add email addresses without having a user account created on our system. Every user will get an email + push notification that they're part of the Circle. Any accounts that are email address only will receive a daily update with the top 3 items from the conversation on what they missed out on, with an opportunity to sign up.
 *
 * @param circleId Required PPCircleId Circle ID
 * @param members Required NSArray Member emails
 * @param callback PPErrorBlock Error callback block
 **/
+ (void)addMembers:(PPCircleId)circleId members:(NSArray * _Nonnull )members callback:(PPErrorBlock _Nonnull )callback;

/**
 * Update Member Status.
 * A circle member can opt-in or opt-out from circle notifications.
 * A circle member can change own status and nickname.
 * A circle admin can also update other users as admins.
 *
 * @param circleKey NSString Circle key for not registered circle members
 * @param circleUserId NSString Circle user ID to update other user by admin
 * @param circleId Required PPCircleId Circle ID
 * @param status PPCircleMemberStatus Member emails
 * @param nickname NSString Member nickname
 * @param admin PPCircleMemberAdmin Member admin
 * @param userId PPUserId User ID to access by administrator
 * @param callback PPErrorBlock Error callback block
 **/
+ (void)updateMemberStatus:(NSString * _Nullable )circleKey circleUserId:(NSString * _Nullable )circleUserId circleId:(PPCircleId)circleId status:(PPCircleMemberStatus)status nickname:(NSString * _Nullable )nickname admin:(PPCircleMemberAdmin)admin userId:(PPUserId)userId callback:(PPErrorBlock _Nonnull )callback;
+ (void)updateMemberStatus:(NSString * _Nullable )circleUserId circleId:(PPCircleId)circleId status:(PPCircleMemberStatus)status nickname:(NSString * _Nullable )nickname userId:(PPUserId)userId callback:(PPErrorBlock _Nonnull )callback __attribute__((deprecated));

/**
 * Remove Members.
 * Only a Circle Administrator may delete other members. Registered users may delete themselves.
 *
 * @param circleId Required PPCircleId Circle ID
 * @param userId PPUserId User ID to access by administrator
 * @param circleUserId Required NSString Circle User ID to delete from the circle
 * @param callback PPErrorBlock Error callback block
 **/
+ (void)removeMembers:(PPCircleId)circleId userId:(PPUserId)userId circleUserId:(NSString * _Nonnull )circleUserId callback:(PPErrorBlock _Nonnull )callback;

#pragma mark - Circle Files

/**
 * Upload File.
 * The client have to upload the file content first and then add a thumbnail. The API will return the thumbnail field equals true, if the cloud was able to generate the thumbnail from the file content.
 * The "Content-Type" header must be like video/..., image/..., audio/... or application/octet-stream (see https://en.wikipedia.org/wiki/Internet_media_type for possible exact values). For example: video/mp4, image/jpeg, audio/mp3. The content type of a thumbnail image is always image/jpeg.
 *
 * @param circleId Required PPCircleId Circle ID
 * @param type Required PPFileFileType File type. By default it is defined from the content type. However this parameter is useful, if a thumbnail with different content type is uploaded frist.
 * @param fileExtension Required NSString File extension (For example, "mp4" or "png")
 * @param duration PPFileDuration Duration of the video in seconds, for reporting to the UI
 * @param rotate PPFileRotate Rotation in degrees. The UI is expected to manually rotat the video back to being upright if this is set.
 * @param thumbnail PPFileThumbnail True - The content is a thumbnail image and the file content will be uploaded later
 * @param expectedSize PPFileSize Expected total size in bytes, if available
 * @param incomplete PPFileIncomplete True - This file content will be replaced or extended later. False - This file is complete
 * @param contentType Required NSString Content-Type header.
 * @param data Required NSData File data
 * @param progressBlock PPCircleFileProgressBlock File upload progress block
 * @param callback PPCircleFileUploadBlock File fragment block containing file reference, used and total file space, twitter share status, and twitter account (if any)
 **/
+ (void)uploadFile:(PPCircleId)circleId type:(PPFileFileType)type fileExtension:(NSString * _Nonnull )fileExtension duration:(PPFileDuration)duration rotate:(PPFileRotate)rotate thumbanil:(PPFileThumbnail)thumbnail expectedSize:(PPFileSize)expectedSize incomplete:(PPFileIncomplete)incomplete contentType:(NSString * _Nonnull )contentType data:(NSData * _Nonnull )data progressBlock:(PPCircleFileProgressBlock _Nullable )progressBlock callback:(PPCircleFileUploadBlock _Nonnull )callback;
+ (void)uploadFile:(PPCircleId)circleId type:(PPFileFileType)type fileExtension:(NSString * _Nonnull )fileExtension duration:(PPFileDuration)duration rotate:(PPFileRotate)rotate thumbanil:(PPFileThumbnail)thumbnail expectedSize:(PPFileSize)expectedSize incomplete:(PPFileIncomplete)incomplete contentType:(NSString * _Nonnull )contentType data:(NSData * _Nonnull )data callback:(PPCircleFileUploadBlock _Nonnull )callback __attribute__((deprecated));

/**
 * Get Files.
 * Return a list of files in the circle.
 *
 * @param circleId Required PPCircleId CircleId
 * @param fileId PPFileId File ID filter
 * @param type PPFileFileType File type
 * @param ownerId PPUserId User ID of the file's owner
 * @param startDate NSDate Start date of the files list
 * @param endDate NSDate End date of the files list
 * @param callback PPCircleFilesBlock Files callback block
 **/
+ (void)getFiles:(PPCircleId)circleId fileId:(PPFileId)fileId type:(PPFileFileType)type ownerId:(PPUserId)ownerId startDate:(NSDate * _Nullable )startDate endDate:(NSDate * _Nullable )endDate callback:(PPCircleFilesBlock _Nonnull )callback;

#pragma mark - Single File Access

/**
 * Upload File Fragment or Thumbnail.
 * Allow to add a fragment to the content of the existing file or upload a thumbnail.
 *
 * @param circleId Required PPCircleId Circle ID
 * @param fileId Required PPFileId Existing file ID
 * @param thumbnail PPFileThumbnail True - The content is a thumbnail image
 * @param incomplete PPFileIncomplete True - The file will be extended later, False - This file is complete
 * @param index PPFileFragmentIndex Fragmen index starting from 0 to identify unique file fragment. It is used for additional control over uploaded data.
 * @param contentType Required NSString Content-Type header.
 * @param data Required NSData File data
 * @param progressBlock PPCircleFileProgressBlock File upload progress block
 * @param callback PPCircleFileUploadFragmentBlock File fragment block containing file reference, used and total file space, twitter share status, and twitter account (if any)
 **/
+ (void)uploadFileFragment:(PPCircleId)circleId fileId:(PPFileId)fileId thumbnail:(PPFileThumbnail)thumbnail incomplete:(PPFileIncomplete)incomplete index:(PPFileFragmentIndex)index contentType:(NSString * _Nonnull )contentType data:(NSData * _Nonnull )data progressBlock:(PPCircleFileProgressBlock _Nullable )progressBlock callback:(PPCircleFileUploadFragmentBlock _Nonnull )callback;
+ (void)uploadFileFragment:(PPCircleId)circleId fileId:(PPFileId)fileId thumbnail:(PPFileThumbnail)thumbnail incomplete:(PPFileIncomplete)incomplete index:(PPFileFragmentIndex)index contentType:(NSString * _Nonnull )contentType data:(NSData * _Nonnull )data callback:(PPCircleFileUploadFragmentBlock _Nonnull )callback __attribute__((deprecated));

/**
 * Download File.
 * The Range HTTP Header is optional, and will only return a chunk of the total content. If used, it is recommended to select a range that is a multiple of 10240 bytes.
 * A temporary API key provided in the query parameter may be used to forward a link to other part of the app. A temporary API key can be obtained by calling the loginByKey API. It is expired soon after receiving.
 * The response will include:
 *      - The file content
 *      - A Content-Type HTTP Header containing the file's content type
 *      - Content range in the Content-Range header, if the Range of the content was requested. This will be in the format of bytes {start}-{end}/{total size}. For example: Content-Range: bytes 21010-47021/47022.
 *      - The Accept-Ranges header containing accepted content range values in bytes. For example "0-47022".
 *      - The Content-Disposition HTTP header that contains the filename when requested.
 * See http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html for a discussion on the header options.
 * HTTP Status Codes:
 *      - 200 (OK): The file content is returned in full.
 *      - 204 (No Content): The file exist, but the content is not available for this request.
 *      - 206 (Partial Content): The file content is partially returned.
 *      - 401 (Unauthorized): The API key is wrong.
 *      - 404 (Not Found): The file does not exists.
 *      - 500 (Internal error): Something went wrong on the server side.
 *
 * @param circleId Required PPCircleId Circle ID
 * @param fileId Required PPFileId File ID to download
 * @param apiKey NSString Temporary API key
 * @param thumbnail PPFileThumbnail True - Download the thumbnail for this file, False - Download the actual file, not the thumbnail, default
 * @param m3u8 PPFileM3U8 True - Download m3u8 file instead of the file content
 * @param attach PPFileAttach Download the file content as an attachments with the Content-Disposition header
 * @param range NSRange Range of bytes to download
 * @param callback PPCircleFileContentBlock File content block
 **/
+ (void)downloadFile:(PPCircleId)circleId fileId:(PPFileId)fileId apiKey:(NSString * _Nullable )apiKey thumbnail:(PPFileThumbnail)thumbnail m3u8:(PPFileM3U8)m3u8 attach:(PPFileAttach)attach range:(NSRange)range callback:(PPCircleFileContentBlock _Nonnull )callback;

/**
 * Get download URL's
 * A client can request temporary download URL's to get file and thumbnail content directly from S3 instead of copying it through the server.
 *
 * @param circleId Required PPCircleId Circle ID
 * @param fileId Required PPFileId File ID to download
 * @param content PPFileContent True - Download the file content URL
 * @param thumbnail PPFileThumbnail True - Download the thumbnail content URL
 * @param m3u8 PPFileM3U8 True - Download m3u8 content URL
 * @param expiration PPFileURLExpiration URL's expiration in milliseconds since the current time
 * @param callback PPCircleFileDownloadURLBlock File content block
 **/
+ (void)getDownloadURL:(PPCircleId)circleId fileId:(PPFileId)fileId content:(PPFileContent)content thumbnail:(PPFileThumbnail)thumbnail m3u8:(PPFileM3U8)m3u8 expiration:(PPFileURLExpiration)expiration callback:(PPCircleFileDownloadURLBlock _Nonnull )callback;

/**
 * Delete a File.
 * Only the owner of the file or an administrator of the circle may delete a file.
 *
 * @param circleId Required PPCircleId Circle ID
 * @param fileId Required PPFileId File ID to delete
 * @param callback PPErrorBlock Error callback block
 **/
+ (void)deleteFile:(PPCircleId)circleId fileId:(PPFileId)fileId callback:(PPErrorBlock _Nonnull )callback;

#pragma mark - Circle Posts

/**
 * Make a post.
 *
 * @param circleId Required PPCircleId Circle ID
 * @param originalPostId PPCirclePostId Original post ID to reply to
 * @param postId PPCirclePostId Post ID to edit content
 * @param text NSString Post text
 * @param fileId PPFileId File ID
 * @param displayAt PPCirclePostDisplayTime Display at time in seconds (since midnight?)
 * @param displayDuration PPCirclePostDisplayTime Display duration time in seconds
 * @param callback PPCirclePostMakeBlock Make post callback block
 **/
+ (void)makePost:(PPCircleId)circleId originalPostId:(PPCirclePostId)originalPostId postId:(PPCirclePostId)postId text:(NSString * _Nullable )text fileId:(PPFileId)fileId displayAt:(PPCirclePostDisplayTime)displayAt displayDuration:(PPCirclePostDisplayTime)displayDuration callback:(PPCirclePostMakeBlock _Nonnull )callback;

/**
 * Get Posts.
 *
 * @param circleIds NSArray Circle ID, multiple values supported
 * @param postId PPCirclePostId Specific original or reply post ID to filter by
 * @param authorId PPUserID Post author user ID
 * @param startDate NSDate Start date of the posts list
 * @param endDate NSDate End date of the posts list
 * @param searchText NSString Search text
 * @param callback PPCirclePostsBlock Posts callback block
 **/
+ (void)getPostsForCircles:(NSArray * _Nullable )circleIds postId:(PPCirclePostId)postId authorId:(PPUserId)authorId startDate:(NSDate * _Nullable )startDate endDate:(NSDate * _Nullable )endDate searchText:(NSString * _Nullable )searchText callback:(PPCirclePostsBlock _Nonnull )callback;
+ (void)getPosts:(PPCircleId)circleId postId:(PPCirclePostId)postId authorId:(PPUserId)authorId startDate:(NSDate * _Nullable )startDate endDate:(NSDate * _Nullable )endDate searchText:(NSString * _Nullable )searchText callback:(PPCirclePostsBlock _Nonnull )callback __attribute__((deprecated));

/**
 * Delete Post.
 * Post can be deleted by the author or circle admin.
 * Deleting a post will delete all attached files. Deleting an original post will delete all replyes and reactions.
 *
 * @param circleId Required PPCircleId Circle ID
 * @param postId PPCirclePostId Specific original or reply post ID to delete
 * @param callback PPErrorBlock Error callback block
 **/
+ (void)deletePost:(PPCircleId)circleId postId:(PPCirclePostId)postId callback:(PPErrorBlock _Nonnull )callback;

#pragma mark - React on Post

/**
 * React.
 *
 * @param circleId Required PPCircleId Circle ID
 * @param postId Required PPCirclePostId Specific original or reply post ID to react on
 * @param type Required PPCircleReactionType Reaction type
 * @param callback PPErrorBlock Error callback block
 **/
+ (void)react:(PPCircleId)circleId postId:(PPCirclePostId)postId type:(PPCircleReactionType)type callback:(PPErrorBlock _Nonnull )callback;

#pragma mark - Circle Devices

/**
 * Get Devices.
 * Retrieve connected device instances linked to users inside the circle.
 *
 * @param circleId Required PPCircleId Circle ID
 * @param callback PPCircleDevicesBlock Devices callback block
 **/
+ (void)getDevices:(PPCircleId)circleId callback:(PPCircleDevicesBlock _Nonnull )callback;


@end
