//
//  PPReports.m
//  Peoplepower
//
//  Created by Destry Teeter on 3/13/18.
//  Copyright © 2020 People Power Company. All rights reserved.
//

#import "PPReports.h"
#import "PPCloudEngine.h"

@implementation PPReports

#pragma mark - Device Alerts

/**
 * Get total device alerts
 * This reports returns total numbers of alerts generated by devices by alert types. User authentication is not required.
 *
 * @param alertType NSString Return only number of this alertType
 * @param callback PPReportAlertTypesBlock Alert Types callback block
 **/
+ (void)getTotalDeviceAlerts:(NSString *)alertType callback:(PPReportAlertTypesBlock)callback {
    NSMutableString *requestString = [[NSMutableString alloc] initWithString:@"totalDeviceAlerts?"];
    
    if(alertType) {
        [requestString appendFormat:@"alertType=%@&", alertType];
    }
    dispatch_queue_t queue = dispatch_queue_create("com.peoplepowerco.ioscore.reports.getTotalDeviceAlerts()", DISPATCH_QUEUE_SERIAL);
    
    PPLogAPI(@"> %s", dispatch_queue_get_label(queue));
    [[PPCloudEngine sharedReportEngine] GET:requestString success:^(NSData *responseData) {
        
        dispatch_async(queue, ^{
            
            NSError *error;
            NSDictionary *root = [PPBaseModel processJSONResponse:responseData originatingClass:NSStringFromClass([self class]) error:&error];
            
            NSMutableArray *alerts;
            
            if(!error) {
                alerts = [[NSMutableArray alloc] initWithCapacity:0];
                for(NSDictionary *alertDict in [root objectForKey:@"alerts"]) {
                    PPDeviceAlert *alert = [PPDeviceAlert initWithDictionary:alertDict];
                    [alerts addObject:alert];
                }
            }
            
            PPLogAPI(@"< %s", dispatch_queue_get_label(DISPATCH_CURRENT_QUEUE_LABEL));
            
            dispatch_async(dispatch_get_main_queue(), ^{
                callback(alerts, error);
            });
        });
    } failure:^(NSError *error) {                
        
        dispatch_async(queue, ^{
            
            PPLogAPI(@"< %s", dispatch_queue_get_label(DISPATCH_CURRENT_QUEUE_LABEL));
            
            dispatch_async(dispatch_get_main_queue(), ^{
                callback(nil, [PPBaseModel resultCodeToNSError:10003 originatingClass:NSStringFromClass([self class]) argument:[NSString stringWithFormat:@"%@", error.userInfo]]);
            });
        });
    }];
}

@end
